USE [DD2975_PreDHA];
GO

INSERT INTO FIELD (field_code, field_name, question) VALUES
('FORM','FORM_TYPE','Type of Form'),
('FORM','FORM_VERSION','DoD Form Version'),
('DEM','LNAME','Last Name'),
('DEM','FNAME','First Name'),
('DEM','MI','Middle Initial'),
('DEM','DODID','DoD ID number (formerly EDIPI)'),
('DEM','D_EVENT','Today''s Date (date on form)'),
('DEM','DOB','Date of Birth'),
('DEM','SEX','Sex'),
('DEM','FORM_SERVICE','Service Branch'),
('DEM','SERVICE_OTHER','Other Defense Agency'),
('DEM','FORM_COMPONENT','Component'),
('DEM','GRADE','Pay Grade'),
('DEM','GRADE_OTHER','Other Grade'),
('DEM','UNIT_NAME','Unit Name'),
('DEM','UNIT_LOC','Duty Station/Location'),
('DEM','PHONE','Current Phone'),
('DEM','CELL','Current Cell Phone'),
('DEM','DSN','Current DSN'),
('DEM','EMAIL','Current Email'),
('DEM','ADDR','Current Address'),
('DEM','CITY','Current CITY'),
('DEM','STATE','Current STATE'),
('DEM','ZIP','Current ZIP Code'),
('DEM','POC_NAME','POC Name'),
('DEM','POC_PHONE','POC Phone'),
('DEM','POC_EMAIL','POC Email'),
('DEM','POC_ADDR','POC Address'),
('DEM','POC_CITY','POC CITY'),
('DEM','POC_STATE','POC STATE'),
('DEM','POC_ZIP','POC ZIP Code'),
('DEM','D_DEPLOY','Estimated Date of deployment'),
('DEM','COUNTRY','Country'),
('DEM','OPERATION_NAME','Name of Operation'),
('DEM','DEPLOY_PREV','Previous deployments'),
('DEM','DEP_PRIMARY','Primary country of last deployment'),
('DEM','D_RET_PREV','Date of Return from previous deployment'),
('1','HEALTH_ASSESSMENT','Overall, how would you rate your health during the PAST MONTH?'),
('2','LIGHT_DUTY','Are you CURRENTLY on a profile, limited duty, waiting on a MOS/Medical Retention Board (MMRB) decision, or being referred to a medical evaluation board (MEB) or physical evaluation board (PEB)?'),
('2','LIGHT_DUTY_REASON','Reason for light duty'),
('3','TOBACCO','How often do you smoke tobacco'),
('4','PREGNANT','Are you pregnant or is there a chance'),
('5','CONTRA_COUNSEL','Do you wish to receive contraceptive counseling?'),
('6','CARE_HEAD','In the past year did you receive care for a head injury?'),
('6','CARE_HEAD_TEXT','Please Explain (head)'),
('7','CURRENT_MEDS','What prescription or over-the- counter medications (including herbals/supplements) for sleep, pain, combat stress, or mental health conditions or concerns are you CURRENTLY taking?'),
('7','CURRENT_MEDS_TEXT','If yes, please list.'),
('8','CARE_MENTAL','In the PAST YEAR did you receive care for any mental health condition or concern such as, but not limited to post traumatic stress disorder (PTSD),depression, anxiety disorder, alcohol abuse or substance abuse?'),
('8','CARE_MENTAL_TEXT','If yes, please explain'),
('9a','NOISES','Noises in your head or ears (such as ringing, buzzing, crickets, humming, tone, etc.) Past month'),
('9b','HEARING','Trouble hearing Past month'),
('10a','ETOH_OFTEN','How often do you have a drink containing alcohol?'),
('10b','ETOH_DAY','How many drinks containing alcohol do you have on a typical day when you are drinking?'),
('10c','ETOH_BINGE','How often do you have six or more drinks on one occasion?'),
('11a','NIGHTMARES','Have you ever had any experience that was so frightening, horrible, or upsetting that, in the PAST MONTH, you: Have had nightmares about it or thought about it when you did not want to?'),
('11b','AVOID_SITUATIONS','Have you ever had any experience that was so frightening, horrible, or upsetting that, in the PAST MONTH, you: Tried hard not to think about it or went out of your way to avoid situations that remind you of it?'),
('11c','ON_GUARD','Have you ever had any experience that was so frightening, horrible, or upsetting that, in the PAST MONTH, you: Were constantly on guard, watchful or easily startled?'),
('11d','DETACHED','Have you ever had any experience that was so frightening, horrible, or upsetting that, in the PAST MONTH, you: Felt numb or detached from others, activities, or your surroundings?'),
('11e','BLAME','Felt guilt or unable to stop blaming yourself or others for the event(s) or any problems the event(s) may have caused?'),
('11f','MEMORIES','Have you been bothered by that problem in the PAST MONTH. Repeated, disturbing memories, thoughts, or images of a stressful experience from the past?'),
('11g','DREAMS','Have you been bothered by that problem in the PAST MONTH. Repeated, disturbing dreams of a stressful experience from the past?'),
('11h','RELIVING','Have you been bothered by that problem in the PAST MONTH. Suddenly acting or feeling as if a stressful experience were happening again (as if you were reliving it)?'),
('11i','UPSET','Have you been bothered by that problem in the PAST MONTH. Feeling very upset when something reminded you of a stressful experience from the past?'),
('11j','PHYS_REACTION','Have you been bothered by that problem in the PAST MONTH. Having physical reactions (e.g., heart pounding, trouble breathing, or sweating) when something reminded you of a stressful experience from the past?'),
('11k','AVOID_THINK','Have you been bothered by that problem in the PAST MONTH. Avoid thinking about or talking about a stressful experience from the past or avoid having feelings related to it?'),
('11l','AVOID_ACTIVITIES','Have you been bothered by that problem in the PAST MONTH. Avoid activities or situations because they remind you of a stressful experience from the past?'),
('11m','TROUBLE_MEMORY','Have you been bothered by that problem in the PAST MONTH. Trouble remembering important parts of a stressful experience from the past?'),
('11n','DISINTEREST','Have you been bothered by that problem in the PAST MONTH. Loss of interest in things that you used to enjoy?'),
('11o','DISTANT','Have you been bothered by that problem in the PAST MONTH. Feeling distant or cut off from other people?'),
('11p','NUMB','Have you been bothered by that problem in the PAST MONTH. Feeling emotionally numb or being unable to have loving feelings for those close to you?'),
('11q','DOOM','Have you been bothered by that problem in the PAST MONTH. Feeling as if your future will somehow be cut short?'),
('11r','INSOMNIA','Have you been bothered by that problem in the PAST MONTH. Trouble falling or staying asleep?'),
('11s','ANGRY_OUTBURSTS','Have you been bothered by that problem in the PAST MONTH. Feeling irritable or having angry outbursts?'),
('11t','CONCENTRATE','Have you been bothered by that problem in the PAST MONTH. Having difficulty concentrating?'),
('11u','WATCHFUL','Have you been bothered by that problem in the PAST MONTH. Being “super alert” or watchful, on guard?'),
('11v','ALERT','Have you been bothered by that problem in the PAST MONTH. Feeling jumpy or easily startled?'),
('11w','LIFE_DIFFICULT','How difficult have these problems (10f. through 10v.) made it for you to do your work, take care of things at home, or get along with other'),
('12a','WEEKS_LITTLE_INTEREST','Over the LAST 2 WEEKS, how often have you been bothered by the following problems? Little interest or pleasure in doing things'),
('12b','WEEKS_DEPRESSED','Over the LAST 2 WEEKS, how often have you been bothered by the following problems? Feeling down, depressed, or hopeless'),
('12c','WEEKS_SLEEP','Over the LAST 2 WEEKS, how often have you been bothered by the following problems? Trouble falling/staying asleep, sleep too much.'),
('12d','WEEKS_TIRED','Over the LAST 2 WEEKS, how often have you been bothered by the following problems? Feeling tired or having little energy'),
('12e','WEEKS_APPETITE','Over the LAST 2 WEEKS, how often have you been bothered by the following problems? Poor appetite or overeating.'),
('12f','WEEKS_FAILURE','Over the LAST 2 WEEKS, how often have you been bothered by the following problems? Feeling bad about yourself – or that you are a failure or have let yourself or your family down.'),
('12g','WEEKS_CONCENTRATE','Over the LAST 2 WEEKS, how often have you been bothered by the following problems? Trouble concentrating on things, such as reading the newspaper or watching television.'),
('12h','WEEKS_LETHARGIC_JUMPY','Over the LAST 2 WEEKS, how often have you been bothered by the following problems? Moving or speaking so slowly that other people could have noticed. Or the opposite – being so fidgety that you have been moving around a lot more than usual.'),
('12i','WEEKS_PROBLEMS','How difficult have these problems (12a.through12h.) made it for you to do your work, take care of things at home, or get along with other people?'),
('13a','STRESSOR_NONE','Over the PAST MONTH, which major life stressors, if any, have you experienced that are a cause of significant concern or make it difficult for you to do your work, take care of things at home, or get along with other people?'),
('13a','STRESSOR_LEGAL','Legal'),
('13a','STRESSOR_MONEY','Financial'),
('13a','STRESSOR_SPIRIT','Spiritual'),
('13a','STRESSOR_SUB','Substance abuse (including alcohol)'),
('13a','STRESSOR_FAM','Family/relationship'),
('13a','STRESSOR_WORK','Employment'),
('13a','STRESSOR_SLEEP','Sleep'),
('13a','STRESSOR_MH','Behavioral health'),
('13a','STRESSOR_OTH','Other'),
('13a','STRESSORS_TEXT','Please list and explain'),
('13b','STRESSORS_HELP','Are you currently in treatment or getting professional help for this concern?'),
('14','CONCERN_OTHER','Are you concerned about any other health condition(s) or health risk exposures not already addressed?'),
('14','CONCERN_TEXT','Please list and explain'),
('','DEPLOYING_TO_PROVIDER','Providers input'),
('','HAS_DEPLOYED_PROVIDER','Providers input'),
('','LAST_RETURNED_PROVIDER','Providers input'),
('HP1','SELF_HEALTH_FOLLOWUP','Self health rating'),
('HP1','SELF_HEALTH_DEPLOYER','Self health rating Deployers Response'),
('HP1','SELF_HEALTH_PROVIDER','Self health rating Providers comments'),
('HP1','MEB_FOLLOWUP','MEB or PEB'),
('HP1','MEB_DEPLOYER','MEB or PEB'),
('HP1','MEB_PROVIDER','MEB or PEB'),
('HP1','MDM_FOLLOWUP','Medical, dental, or mental health concern'),
('HP1','MDM_DEPLOYER','Medical, dental, or mental health concern'),
('HP1','MDM_PROVIDER','Medical, dental, or mental health concern'),
('HP1','PREGNANT_FOLLOWUP','I am or may be pregnant'),
('HP1','PREGNANT_DEPLOYER','I am or may be pregnant'),
('HP1','PREGNANT_PROVIDER','I am or may be pregnant'),
('HP1','DELIVERED6_FOLLOWUP','Pregnant or just delivered within the past 6-months'),
('HP1','DELIVERED6_DEPLOYER','Pregnant or just delivered within the past 6-months'),
('HP1','DELIVERED6_PROVIDER','Pregnant or just delivered within the past 6-months'),
('HP1','DELIVERED12_FOLLOWUP','Pregnant and delivered 6 ~ 12 months ago'),
('HP1','DELIVERED12_DEPLOYER','Pregnant and delivered 6 ~ 12 months ago'),
('HP1','DELIVERED12_PROVIDER','Pregnant and delivered 6 ~ 12 months ago'),
('HP1','DELIVERED00_FOLLOWUP','Not pregnant or delivered in past 12 months'),
('HP1','DELIVERED00_DEPLOYER','Not pregnant or delivered in past 12 months'),
('HP1','DELIVERED00_PROVIDER','Not pregnant or delivered in past 12 months'),
('HP1','CONTRA_COUNSEL_FOLLOWUP','Contraceptive counseling'),
('HP1','CONTRA_COUNSEL_DEPLOYER','Contraceptive counseling'),
('HP1','CONTRA_COUNSEL_PROVIDER','Contraceptive counseling'),
('HP1','HEAD_FOLLOWUP','Head injury'),
('HP1','HEAD_DEPLOYER','Head injury'),
('HP1','HEAD_PROVIDER','Head injury'),
('HP1','MED_FOLLOWUP','Medications'),
('HP1','MED_DEPLOYER','Medications'),
('HP1','MED_PROVIDER','Medications'),
('HP1','HX_MH_FOLLOWUP','History of mental Health Care'),
('HP1','HX_MH_DEPLOYER','History of mental Health Care'),
('HP1','HX_MH_PROVIDER','History of mental Health Care'),
('HP2a','HEARING_REPORTED','Did deployer mark he/she bothered by noises in ears or trouble hearing'),
('HP2b','REF_HEARING','Is referral indicated for hearing problem'),
('HP2b','REF_HEARING_NEG','Why not referred'),
('HP2b','REF_HEARING_TEXT','Other reason for referral'),
('HP3a','AUDITC_SCREEN','Deployer''s AUDIT-C screening score'),
('HP3a','ETOH_WEEK_PROVIDER','Number of drinks per week'),
('HP3a','ETOH_TOTAL_PROVIDER','Number of drinks per occasion'),
('HP3b','REF_ETOH','Referral indicated for evaluation ETOH'),
('HP3b','REF_ETOH_NEG','Reason for no referral'),
('HP3b','REF_ETOH_TEXT','Other reason for referral'),
('HP4a','PTSD_REPORTED','Did deployer mark yes on three or more of questions 10a. through 10e?'),
('HP4b','PCLC_SCORE','If yes, deployer’s responses to questions 10f. through 10v. resulted in a PCL-C score of and the deployer’s response to level of impairment with life events (10w.) is indicated in the table below'),
('HP4b','PCLC_INCOMPLETE','10f. through 10w. were not answered or are incomplete'),
('HP4b','PCLC_MATRIX','PTSD Intervention Matrix, Self-Reported Level of Functioning'),
('HP4c','REF_PTSD','Referral indicated for PTSD'),
('HP4c','REF_PTSD_NEG','Reason for no referral'),
('HP4c','REF_PTSD_TEXT','Other reason for referral'),
('HP5a','DEPRESSION_REPORTED','Did deployer mark “More than half the days” or “Nearly every day” on question 11a. or 11b.?'),
('HP5b','PHQ8_SCORE','If yes, deployer’s responses to questions 11a. through 11h. resulted in a total PHQ-8 score of and the deployer’s response to level of impairment with life events (11i.) is indicated in the table below.'),
('HP5b','PHQ8_INCOMPLETE','11c. through 11i. were not answered or incomplete.'),
('HP5b','PHQ8_MATRIX','Depression Intervention Matrix, Self-Reported Level of Functioning'),
('HP5c','REF_DEPRESSION','Referral for depression education'),
('HP5c','REF_DEPRESSION_NEG','Reason for no referral'),
('HP5c','REF_DEPRESSION_TEXT','Other reason for referral'),
('HP6a','STRESSORS_REPORTED','Did deployer mark they have a concern or a difficulty with a major life stressor?'),
('HP6a','STRESSORS_DEPLOYERS_CONCERN','Deployer''s Concern'),
('HP6b','STRESSORS_COMMENTS','If yes, ask additional questions to determine level of problem:'),
('HP6c','REF_STRESSORS','Referral for STRESSORS'),
('HP6c','REF_STRESSORS_NEG','Reason for no referral'),
('HP6c','REF_STRESSORS_OTHER','Other reason for referral'),
('HP7a','SUICIDE_A','Over the PAST MONTH, have you wished you were dead or wished you could go to sleep and not wake up?'),
('HP7b','SUICIDE_B','Have you actually had any thoughts of killing yourself?'),
('HP7c','SUICIDE_C','Over the PAST MONTH, have you been thinking about how you might do this?'),
('HP7d','SUICIDE_D','Over the PAST MONTH, have you had these thoughts and had some intention of acting on them?'),
('HP7e1','SUICIDE_E1','Over the PAST MONTH, have you started to work out or worked out the details of how to kill yourself?'),
('HP7e2','SUICIDE_E2','At any time in the PAST MONTH, did you intend to carry out this plan?'),
('HP7f1','SUICIDE_F1','In your lifetime, have you ever done anything, started to do anything, or prepared to do anything to end your life?'),
('HP7f2','SUICIDE_F2','Was this within the past three months?'),
('HP7g','SUICIDE_G_TEXT','Conduct further risk assessment'),
('HP7h','SUICIDE_RISK','Does deployer pose a current risk for harm to self?'),
('HP8a','VIOLENCE','Over the past month have you had thoughts or concerns that you might hurt or lose control with someone?”'),
('HP8a','VIOLENCE_TEXT','Comments on violence/harm eval'),
('HP8b','VIOLENCE_RISK','Does member pose a current risk to others?'),
('HP8b','VIOLENCE_RISK_TEXT','Explain 8B'),
('HP9','MED_HX_REV','Medical History Review'),
('HP9a','SIGNIF_FDN','Significant findings'),
('HP9b','MED_LIMIT_DEPLOY','Evidence of deployment limiting condition'),
('HP10','DEP_DEC_FORM','Deployer declined to complete form'),
('HP10','DEP_DEC_ASSESS','Deployer declined to complete interview'),
('HP11a','REFER_NONE','No concerns identified'),
('HP11b','REFER_PH','Concerns identified: Physical health'),
('HP11c','REFER_DENTAL','Concerns identified: Dental health'),
('HP11d','REFER_ETOH','Concerns identified: Alcohol use'),
('HP11e','REFER_PTSD','Concerns identified: PTSD symptoms'),
('HP11f','REFER_DEPRESSION','Concerns identified: Depression symptoms'),
('HP11g','REFER_MH','Concerns identified: Mental health symptoms'),
('HP11h','REFER_HARM','Concerns identified: Risk of self-harm'),
('HP11i','REFER_VIOLENCE','Concerns identified: Risk of violence'),
('HP11j','REFER_OTHER','Concerns identified: Other'),
('HP11j','REFER_OTHER_TEXT','Concerns identified: Other (list)'),
('HP12a','REFTIME_PRIMARY','Referral indicated - Primary Care, Family Practice, Internal Medicine'),
('HP12b','REFTIME_MENTAL_PRIMARY','Referral indicated - Behavioral Health in Primary Care'),
('HP12c','REFTIME_MENTAL_SPECIAL','Referral indicated - Mental Health'),
('HP12d','REFTIME_DENTAL','Referral indicated - Dental'),
('HP12e','REFTIME_OTHER_SPEC','Referral indicated - Other specialty care'),
('HP12e','REFTIME_AUDIOLOGY','Referral indicated - Audiology'),
('HP12e','REFTIME_DERM','Referral indicated - dermatologic'),
('HP12e','REFTIME_GYN','Referral indicated - OB/GYN'),
('HP12e','REFTIME_PT','Referral indicated - PT'),
('HP12e','REFTIME_TBI','Referral indicated -TBI/Rehab Med'),
('HP12e','REFTIME_PODIATRY','Referral indicated - Podiatry'),
('HP12e','REFTIME_SPEC_OTHER','Referral to other specialty care listed'),
('HP12e','REFTIME_SPEC_OTH_TEXT','List of other specialty referral'),
('HP12f','REFTIME_CARE','Referral to Case manager'),
('HP12g','REFTIME_ABUSE','Referral to Substance abuse program'),
('HP12h','REFTIME_OTHER','Other referral listed'),
('HP12h','REFTIME_OTHER_TEXT','List of other specialty referral'),
('HP13','REFTIME_COMMENTS','Referral comments'),
('HP14','MED_DISP','Final Medical Disposition'),
('HP16','APPOINTMENT_ASSIST','Appointment Assistance'),
('HP16','APPOINT_ASSIST_TEXT','Appointment assistance text'),
('HP16','CONTRACT_SUP','Contract support'),
('HP16','CONTRACT_SUP_TEXT','Contract support text'),
('HP16','COMMUNITY','Community Service'),
('HP16','COMMUNITY_TEXT','Community Service text'),
('HP16','CHAPLAIN','Chaplain'),
('HP16','HEALTH_ED','Health Education and Information'),
('HP16','HEALTH_RESOURCES','Health Care Benefits and Resources Information'),
('HP16','IN_TRANS','In Transition'),
('HP16','FAM_SUPPORT','Family Support'),
('HP16','ONE_SOURCE','Military one source'),
('HP16','TRICARE','TRICARE PROVIDER'),
('HP16','VA_MED','VA Medical Center or Community Clinic'),
('HP16','VET','Vet Center'),
('HP16','OTHER_SUPPORT','Other Supplemental services recommended'),
('HP16','OTHER_SUPPORT_TEXT','Other Supplemental services recommended text'),
('HP16','APPOINTMENT_NONE','No Supplemental Services Required'),
('HP16','PROVIDER_NAME','Provider''s Name'),
('HP16','CERTIFY_DATE','Date Certified'),
('HP16','PROVIDER_TITLE','Provider''s title'),
('HP16','CERT_PROVIDER','Provider''s Signature');